-- Add detailed wine rating fields based on Danish wine rating system
ALTER TABLE wine_ratings 
ADD COLUMN appearance_color TEXT,
ADD COLUMN appearance_intensity TEXT,
ADD COLUMN appearance_clarity TEXT,
ADD COLUMN appearance_viscosity TEXT,
ADD COLUMN appearance_comments TEXT,
ADD COLUMN aroma_condition TEXT,
ADD COLUMN aroma_intensity TEXT,
ADD COLUMN aroma_primary TEXT,
ADD COLUMN aroma_secondary TEXT,
ADD COLUMN aroma_tertiary TEXT,
ADD COLUMN aroma_comments TEXT,
ADD COLUMN palate_sweetness TEXT,
ADD COLUMN palate_acidity TEXT,
ADD COLUMN palate_tannin TEXT,
ADD COLUMN palate_body TEXT,
ADD COLUMN palate_flavor_primary TEXT,
ADD COLUMN palate_flavor_secondary TEXT,
ADD COLUMN palate_flavor_tertiary TEXT,
ADD COLUMN palate_complexity TEXT,
ADD COLUMN palate_finish TEXT,
ADD COLUMN palate_balance TEXT,
ADD COLUMN palate_comments TEXT;