// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twjmwhtrkfjvclmooqfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3am13aHRya2ZqdmNsbW9vcWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTU4OTMsImV4cCI6MjA3MTc5MTg5M30.Hm0QGn7TJXy2IGfg0wacNYs-3vBvftjpUflnrvcvv_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});